version: '3.7'
services:
  postgres:
    image: postgres:13.5
    restart: always
    command: postgres -c listen_addresses='*'
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - data:/var/lib/postgresql/data
  nginx:
    image: nginx:1.19.6
    volumes:
      - ./Dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./Dockerfiles/nginx/certs/_wildcard.local.test.pem:/etc/nginx/_wildcard.local.test.pem
      - ./Dockerfiles/nginx/certs/_wildcard.local.test-key.pem:/etc/nginx/_wildcard.local.test-key.pem
      - ./data/nginx:/var/log/nginx
    ports:
      - 443:443
    depends_on:
      - 'app'
  app:
    build:
      context: .
      dockerfile: ./Dockerfiles/app/Dockerfile
      args:
        TOKEN: $TOKEN
    volumes:
      - ./:/myapp
    ports:
      - 4000:4000 # Emulator Suite UI
      - 5000:5000 # Firebase Hosting
      - 8080:8080 # Firestore
      - 5001:5001 # Cloud Functions
      - 9005:9005 # Firebase Login
      - 9099:9099 # Firebase Auth
    links:
      - postgres
volumes:
  data:

